CI Integration (#1)
* Add: Eslint Configuration

* Update: Eslint YML

* Update: Packages related to ESLint

* Add: Legacy Peer Deps flags

* Update: Eslint Config to include sarif export

* Update: .gitignore and export sarif func

* Add: Continue on Error flag for debugging purposes

* Update: eslint config file and eslint yml to include src/ folder

* Update: Eslint Config

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -11,12 +11,13 @@ name: ESLint
 
 on:
   push:
-    branches: [ "main" ]
+    branches:
+      - "**"
   pull_request:
-    # The branches below must be a subset of the branches above
-    branches: [ "main" ]
+    branches:
+      - "**"
   schedule:
-    - cron: '36 5 * * 5'
+    - cron: "36 5 * * 5"
 
 jobs:
   eslint:
@@ -29,24 +30,16 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
       - name: Install ESLint
         run: |
-          npm install eslint@8.10.0
-          npm install @microsoft/eslint-formatter-sarif@3.1.0
-
+          npm install eslint@8.10.0 --legacy-peer-deps
+          npm install @microsoft/eslint-formatter-sarif@3.1.0 --legacy-peer-deps
+      - name: Debug ESLint SARIF File
+        run: ls -lah eslint-results.sarif || echo "File not found"
       - name: Run ESLint
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
-        run: npx eslint .
-          --config .eslintrc.js
-          --ext .js,.jsx,.ts,.tsx
-          --format @microsoft/eslint-formatter-sarif
-          --output-file eslint-results.sarif
+        run: npm run lint
         continue-on-error: true
-
-      - name: Upload analysis results to GitHub
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: eslint-results.sarif
-          wait-for-processing: true
+      - name: List files in the current directory
+        run: ls -lah
