Update: Eslint Config to include sarif export

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -35,19 +35,18 @@ jobs:
         run: |
           npm install eslint@8.10.0 --legacy-peer-deps
           npm install @microsoft/eslint-formatter-sarif@3.1.0 --legacy-peer-deps
+      - name: Debug ESLint SARIF File
+        run: ls -lah eslint-results.sarif || echo "File not found"
 
       - name: Run ESLint
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
-        run: npx eslint .
-          --config .eslintrc.js
-          --ext .js,.jsx,.ts,.tsx
-          --format @microsoft/eslint-formatter-sarif
-          --output-file eslint-results.sarif
+        run: npx eslint "**/*.{js,jsx,ts,tsx}" --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
         continue-on-error: true
-
       - name: Upload analysis results to GitHub
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: eslint-results.sarif
           wait-for-processing: true
+      - name: List files in the current directory
+        run: ls -alh
